In [3]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier

In [4]:
df = pd.read_csv('churn_data.csv')

In [5]:
df.head()

,Unnamed: 0,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,...,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,0,29.85,29.85,0,0,1,0,0,1,...,0,1,0,1,0,0,0,0,0,0
1,1,0,56.95,1889.50,0,1,0,0,1,0,...,0,0,0,0,1,0,1,0,0,0
2,2,0,53.85,108.15,1,1,0,0,1,0,...,0,1,0,0,1,0,0,0,0,0
3,3,0,42.30,1840.75,0,1,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
4,4,0,70.70,151.65,1,0,0,0,1,0,...,0,1,0,1,0,0,0,0,0,0

In [6]:
df = df.drop('Unnamed: 0',axis=1)

In [7]:
df.head()

,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,0,0,1,0,0,1,0,...,0,1,0,1,0,0,0,0,0,0
1,0,56.95,1889.50,0,1,0,0,1,0,0,...,0,0,0,0,1,0,1,0,0,0
2,0,53.85,108.15,1,1,0,0,1,0,0,...,0,1,0,0,1,0,0,0,0,0
3,0,42.30,1840.75,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
4,0,70.70,151.65,1,0,0,0,1,0,0,...,0,1,0,1,0,0,0,0,0,0

In [8]:
#Creating X and Y
X = df.drop('Churn',axis=1)
y = df['Churn']

In [9]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2
)

### Decision Tree Classifier

In [10]:
dt_model = DecisionTreeClassifier(criterion ='gini',random_state= 100,max_depth=6,min_samples_leaf= 8)

In [11]:
dt_model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [12]:
y_pred = dt_model.predict(X_test)

In [13]:
y_pred

array([0, 1, 0, ..., 0, 0, 0])

In [14]:
dt_model.score(X_test,y_pred)

1.0

In [15]:
print(classification_report(y_test,y_pred,labels = [0,1]))

              precision    recall  f1-score   support

           0       0.83      0.90      0.87      1061
           1       0.60      0.45      0.51       346

    accuracy                           0.79      1407
   macro avg       0.71      0.68      0.69      1407
weighted avg       0.78      0.79      0.78      1407

In [16]:
print(confusion_matrix(y_test,y_pred))

[[955 106]
 [190 156]]

In [17]:
#To resolve the issue of IMBALANCED DATA
from imblearn.combine import SMOTEENN

smote_enn = SMOTEENN(random_state=42)
X_resampled, y_resampled = smote_enn.fit_resample(X, y)

In [18]:
Xr_train,Xr_test,yr_train,yr_test = train_test_split(
    X_resampled,y_resampled,test_size=0.2
)

In [19]:
model_dt_smote = DecisionTreeClassifier(criterion = 'gini',random_state = 100,max_depth=6,min_samples_leaf= 8)

In [20]:
model_dt_smote.fit(Xr_train,yr_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [21]:
y_pred_smote = model_dt_smote.predict(Xr_test)

In [22]:
print(classification_report(yr_test,y_pred_smote,labels = [0,1]))

              precision    recall  f1-score   support

           0       0.96      0.89      0.93       523
           1       0.92      0.97      0.94       644

    accuracy                           0.94      1167
   macro avg       0.94      0.93      0.94      1167
weighted avg       0.94      0.94      0.94      1167

### Random Forest Classifier

In [23]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
model_rf = RandomForestClassifier(n_estimators=100,criterion='gini',random_state=100,max_depth=6,min_samples_leaf=8)
model_rf.fit(X_train,y_train)
y_pred_rf = model_rf.predict(X_test)

In [25]:
print(classification_report(y_test,y_pred_rf, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.83      0.92      0.88      1061
           1       0.65      0.43      0.52       346

    accuracy                           0.80      1407
   macro avg       0.74      0.68      0.70      1407
weighted avg       0.79      0.80      0.79      1407

In [27]:
sm = SMOTEENN()
X_resampled, y_resampled = smote_enn.fit_resample(X, y)

In [28]:
Xr_train,Xr_test,yr_train,yr_test = train_test_split(X_resampled,y_resampled,test_size = 0.2)

In [29]:
model_smote_rf = RandomForestClassifier(n_estimators=100,criterion='gini',random_state=100,max_depth=6,min_samples_leaf=8)

In [30]:
model_smote_rf.fit(Xr_train,yr_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [32]:
y_pred_smote_rf = model_smote_rf.predict(Xr_test)

In [33]:
print(classification_report(yr_test,y_pred_smote_rf,labels=[0,1]))

              precision    recall  f1-score   support

           0       0.95      0.89      0.92       520
           1       0.92      0.96      0.94       647

    accuracy                           0.93      1167
   macro avg       0.94      0.93      0.93      1167
weighted avg       0.93      0.93      0.93      1167

In [35]:
print(confusion_matrix(yr_test,y_pred_smote_rf))

[[465  55]
 [ 23 624]]

In [44]:
from imblearn.pipeline import Pipeline

pipeline = Pipeline([
    ("smoteenn", SMOTEENN()),
    ("rf", RandomForestClassifier(
        n_estimators=100,
        max_depth=6,
        random_state=100
    ))
])

pipeline.fit(X_train, y_train)
pickle.dump(pipeline, open("model.pkl", "wb"))